services:
  db:
    image: postgres:16
    container_name: aegispraxis-db
    restart: always
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aegisnet

volumes:
  postgres_data:

networks:
  aegisnet:
    driver: bridge
